# Base16 Madrid
# Scheme author: xscriptor (https://github.com/xscriptor)
# Template author: Tinted Theming: (https://github.com/tinted-theming)

# default statusbar colors
set-option -g status-style "fg=#1a1a1a,bg=#fafafa"

# default window title colors
set-window-option -g window-status-style "fg=#1a1a1a,bg=#fafafa"

# active window title colors
set-window-option -g window-status-current-style "fg=#8a6408,bg=#fafafa"

# pane border
set-option -g pane-border-style "fg=#eaeaea"
set-option -g pane-active-border-style "fg=#686868"

# message text
set-option -g message-style "fg=#121212,bg=#eaeaea"

# pane number display
set-option -g display-panes-active-colour "#686868"
set-option -g display-panes-colour "#eaeaea"

# clock
set-window-option -g clock-mode-colour "#007a9e"

# copy mode highlight
set-window-option -g mode-style "fg=#686868,bg=#eaeaea"

# bell
set-window-option -g window-status-bell-style "fg=#fafafa,bg=#990026"

# style for window titles with activity
set-window-option -g window-status-activity-style "fg=#1a1a1a,bg=#fafafa"

# style for command messages
set-option -g message-command-style "fg=#121212,bg=#eaeaea"

# Optional active/inactive pane state
# BASE16_TMUX_OPTION_ACTIVE is a legacy variable
if-shell '[ "$TINTED_TMUX_OPTION_ACTIVE" = "1" ] || [ "$BASE16_TMUX_OPTION_ACTIVE" = "1" ]' {
  set-window-option -g window-active-style "fg=#1a1a1a,bg=#fafafa"
  set-window-option -g window-style "fg=#1a1a1a,bg=#fafafa"
}

# Optional statusbar
# BASE16_TMUX_OPTION_STATUSBAR is a legacy variable
if-shell '[ "$TINTED_TMUX_OPTION_STATUSBAR" = "1" ] || [ "$BASE16_TMUX_OPTION_STATUSBAR" = "1" ]' {
  set-option -g status "on"
  set-option -g status-justify "left"
  set-option -g status-left "#[fg=#1a1a1a,bg=#dfdfdf] #S #[fg=#dfdfdf,bg=#fafafa,nobold,noitalics,nounderscore]"
  set-option -g status-left-length "80"
  set-option -g status-left-style none
  set-option -g status-right "#[fg=#eaeaea,bg=#fafafa nobold, nounderscore, noitalics]#[fg=#686868,bg=#eaeaea] %Y-%m-%d  %H:%M #[fg=#1a1a1a,bg=#eaeaea,nobold,noitalics,nounderscore]#[fg=#fafafa,bg=#1a1a1a] #h "
  set-option -g status-right-length "80"
  set-option -g status-right-style none
  set-window-option -g window-status-current-format "#[fg=#fafafa,bg=#8a6408,nobold,noitalics,nounderscore]#[fg=#eaeaea,bg=#8a6408] #I #[fg=#eaeaea,bg=#8a6408,bold] #W#{?window_zoomed_flag,*Z,} #[fg=#8a6408,bg=#fafafa,nobold,noitalics,nounderscore]"
  set-window-option -g window-status-format "#[fg=#fafafa,bg=#eaeaea,noitalics]#[fg=#121212,bg=#eaeaea] #I #[fg=#121212,bg=#eaeaea] #W#{?window_zoomed_flag,*Z,} #[fg=#eaeaea,bg=#fafafa,noitalics]"
  set-window-option -g window-status-separator ""
}

# vim: set ft=tmux tw=0:
