# Base16 Serendipity Morning
# Scheme author: Micheal Andreuzza (https://michaelandreuzza.com/)
# Template author: Tinted Theming: (https://github.com/tinted-theming)

# default statusbar colors
set-option -g status-style "fg=#3f4363,bg=#f6f7fb"

# default window title colors
set-window-option -g window-status-style "fg=#3f4363,bg=#f6f7fb"

# active window title colors
set-window-option -g window-status-current-style "fg=#785fd0,bg=#f6f7fb"

# pane border
set-option -g pane-border-style "fg=#eaebee"
set-option -g pane-active-border-style "fg=#505575"

# message text
set-option -g message-style "fg=#3f4363,bg=#eaebee"

# pane number display
set-option -g display-panes-active-colour "#505575"
set-option -g display-panes-colour "#eaebee"

# clock
set-window-option -g clock-mode-colour "#6288d8"

# copy mode highlight
set-window-option -g mode-style "fg=#505575,bg=#eaebee"

# bell
set-window-option -g window-status-bell-style "fg=#f6f7fb,bg=#c25a4d"

# style for window titles with activity
set-window-option -g window-status-activity-style "fg=#3f4363,bg=#f6f7fb"

# style for command messages
set-option -g message-command-style "fg=#3f4363,bg=#eaebee"

# Optional active/inactive pane state
# BASE16_TMUX_OPTION_ACTIVE is a legacy variable
if-shell '[ "$TINTED_TMUX_OPTION_ACTIVE" = "1" ] || [ "$BASE16_TMUX_OPTION_ACTIVE" = "1" ]' {
  set-window-option -g window-active-style "fg=#3f4363,bg=#f6f7fb"
  set-window-option -g window-style "fg=#3f4363,bg=#f6f7fb"
}

# Optional statusbar
# BASE16_TMUX_OPTION_STATUSBAR is a legacy variable
if-shell '[ "$TINTED_TMUX_OPTION_STATUSBAR" = "1" ] || [ "$BASE16_TMUX_OPTION_STATUSBAR" = "1" ]' {
  set-option -g status "on"
  set-option -g status-justify "left"
  set-option -g status-left "#[fg=#3f4363,bg=#eaebee] #S #[fg=#eaebee,bg=#f6f7fb,nobold,noitalics,nounderscore]"
  set-option -g status-left-length "80"
  set-option -g status-left-style none
  set-option -g status-right "#[fg=#eaebee,bg=#f6f7fb nobold, nounderscore, noitalics]#[fg=#505575,bg=#eaebee] %Y-%m-%d  %H:%M #[fg=#3f4363,bg=#eaebee,nobold,noitalics,nounderscore]#[fg=#f6f7fb,bg=#3f4363] #h "
  set-option -g status-right-length "80"
  set-option -g status-right-style none
  set-window-option -g window-status-current-format "#[fg=#f6f7fb,bg=#785fd0,nobold,noitalics,nounderscore]#[fg=#eaebee,bg=#785fd0] #I #[fg=#eaebee,bg=#785fd0,bold] #W#{?window_zoomed_flag,*Z,} #[fg=#785fd0,bg=#f6f7fb,nobold,noitalics,nounderscore]"
  set-window-option -g window-status-format "#[fg=#f6f7fb,bg=#eaebee,noitalics]#[fg=#3f4363,bg=#eaebee] #I #[fg=#3f4363,bg=#eaebee] #W#{?window_zoomed_flag,*Z,} #[fg=#eaebee,bg=#f6f7fb,noitalics]"
  set-window-option -g window-status-separator ""
}

# vim: set ft=tmux tw=0:
