# Base16 Sequoia Monochrome Dark
# Scheme author: Micheal Andreuzza (https://michaelandreuzza.com/)
# Template author: Tinted Theming: (https://github.com/tinted-theming)

# default statusbar colors
set-option -g status-style "fg=#868690,bg=#0f1014"

# default window title colors
set-window-option -g window-status-style "fg=#868690,bg=#0f1014"

# active window title colors
set-window-option -g window-status-current-style "fg=#d3d5de,bg=#0f1014"

# pane border
set-option -g pane-border-style "fg=#111216"
set-option -g pane-active-border-style "fg=#575861"

# message text
set-option -g message-style "fg=#868690,bg=#111216"

# pane number display
set-option -g display-panes-active-colour "#575861"
set-option -g display-panes-colour "#111216"

# clock
set-window-option -g clock-mode-colour "#7c829d"

# copy mode highlight
set-window-option -g mode-style "fg=#575861,bg=#111216"

# bell
set-window-option -g window-status-bell-style "fg=#0f1014,bg=#999eb2"

# style for window titles with activity
set-window-option -g window-status-activity-style "fg=#868690,bg=#0f1014"

# style for command messages
set-option -g message-command-style "fg=#868690,bg=#111216"

# Optional active/inactive pane state
# BASE16_TMUX_OPTION_ACTIVE is a legacy variable
if-shell '[ "$TINTED_TMUX_OPTION_ACTIVE" = "1" ] || [ "$BASE16_TMUX_OPTION_ACTIVE" = "1" ]' {
  set-window-option -g window-active-style "fg=#868690,bg=#0f1014"
  set-window-option -g window-style "fg=#868690,bg=#0f1014"
}

# Optional statusbar
# BASE16_TMUX_OPTION_STATUSBAR is a legacy variable
if-shell '[ "$TINTED_TMUX_OPTION_STATUSBAR" = "1" ] || [ "$BASE16_TMUX_OPTION_STATUSBAR" = "1" ]' {
  set-option -g status "on"
  set-option -g status-justify "left"
  set-option -g status-left "#[fg=#868690,bg=#111216] #S #[fg=#111216,bg=#0f1014,nobold,noitalics,nounderscore]"
  set-option -g status-left-length "80"
  set-option -g status-left-style none
  set-option -g status-right "#[fg=#111216,bg=#0f1014 nobold, nounderscore, noitalics]#[fg=#575861,bg=#111216] %Y-%m-%d  %H:%M #[fg=#868690,bg=#111216,nobold,noitalics,nounderscore]#[fg=#0f1014,bg=#868690] #h "
  set-option -g status-right-length "80"
  set-option -g status-right-style none
  set-window-option -g window-status-current-format "#[fg=#0f1014,bg=#d3d5de,nobold,noitalics,nounderscore]#[fg=#111216,bg=#d3d5de] #I #[fg=#111216,bg=#d3d5de,bold] #W#{?window_zoomed_flag,*Z,} #[fg=#d3d5de,bg=#0f1014,nobold,noitalics,nounderscore]"
  set-window-option -g window-status-format "#[fg=#0f1014,bg=#111216,noitalics]#[fg=#868690,bg=#111216] #I #[fg=#868690,bg=#111216] #W#{?window_zoomed_flag,*Z,} #[fg=#111216,bg=#0f1014,noitalics]"
  set-window-option -g window-status-separator ""
}

# vim: set ft=tmux tw=0:
