# Base24 Oslo
# Scheme author: xscriptor (https://github.com/xscriptor)
# Template author: Tinted Theming: (https://github.com/tinted-theming)

# default statusbar colors
set-option -g status-style "fg=#7a808e,bg=#474c59"

# default window title colors
set-window-option -g window-status-style "fg=#7a808e,bg=#474c59"

# active window title colors
set-window-option -g window-status-current-style "fg=#f0a45d,bg=#474c59"

# pane border
set-option -g pane-border-style "fg=#474c59"
set-option -g pane-active-border-style "fg=#7a808e"

# message text
set-option -g message-style "fg=#bcc1cc,bg=#4c515e"

# pane number display
set-option -g display-panes-active-colour "#7a808e"
set-option -g display-panes-colour "#474c59"

# clock
set-window-option -g clock-mode-colour "#4aa5f0"

# copy mode highlight
set-window-option -g mode-style "fg=#7a808e,bg=#4c515e"

# bell
set-window-option -g window-status-bell-style "fg=#3f4451,bg=#e05561"

# style for window titles with activity
set-window-option -g window-status-activity-style "fg=#abb2bf,bg=#474c59"

# style for command messages
set-option -g message-command-style "fg=#bcc1cc,bg=#4c515e"

# Optional active/inactive pane state
if-shell '[ "$TINTED_TMUX_OPTION_ACTIVE" = "1" ]' {
  set-window-option -g window-active-style "fg=#abb2bf,bg=#3f4451"
  set-window-option -g window-style "fg=#abb2bf,bg=#474c59"
}

# Optional statusbar
if-shell '[ "$TINTED_TMUX_OPTION_STATUSBAR" = "1" ]' {
  set-option -g status "on"
  set-option -g status-justify "left"
  set-option -g status-left "#[fg=#abb2bf,bg=#6c727f] #S #[fg=#6c727f,bg=#474c59,nobold,noitalics,nounderscore]"
  set-option -g status-left-length "80"
  set-option -g status-left-style none
  set-option -g status-right "#[fg=#4c515e,bg=#474c59 nobold, nounderscore, noitalics]#[fg=#7a808e,bg=#4c515e] %Y-%m-%d  %H:%M #[fg=#abb2bf,bg=#4c515e,nobold,noitalics,nounderscore]#[fg=#474c59,bg=#abb2bf] #h "
  set-option -g status-right-length "80"
  set-option -g status-right-style none
  set-window-option -g window-status-current-format "#[fg=#474c59,bg=#d18f52,nobold,noitalics,nounderscore]#[fg=#4c515e,bg=#d18f52] #I #[fg=#4c515e,bg=#d18f52,bold] #W#{?window_zoomed_flag,*Z,}} #[fg=#d18f52,bg=#474c59,nobold,noitalics,nounderscore]"
  set-window-option -g window-status-format "#[fg=#474c59,bg=#4c515e,noitalics]#[fg=#bcc1cc,bg=#4c515e] #I #[fg=#bcc1cc,bg=#4c515e] #W#{?window_zoomed_flag,*Z,}} #[fg=#4c515e,bg=#474c59,noitalics]"
  set-window-option -g window-status-separator ""
}

# vim: set ft=tmux tw=0:
