# Base16 Serendipity Midnight
# Scheme author: Micheal Andreuzza (https://michaelandreuzza.com/)
# Template author: Tinted Theming: (https://github.com/tinted-theming)

# default statusbar colors
set-option -g status-style "fg=#dee0ef,bg=#151726"

# default window title colors
set-window-option -g window-status-style "fg=#dee0ef,bg=#151726"

# active window title colors
set-window-option -g window-status-current-style "fg=#a78bfa,bg=#151726"

# pane border
set-option -g pane-border-style "fg=#1c1e2d"
set-option -g pane-active-border-style "fg=#8d8f9e"

# message text
set-option -g message-style "fg=#dee0ef,bg=#1c1e2d"

# pane number display
set-option -g display-panes-active-colour "#8d8f9e"
set-option -g display-panes-colour "#1c1e2d"

# clock
set-window-option -g clock-mode-colour "#94b8ff"

# copy mode highlight
set-window-option -g mode-style "fg=#8d8f9e,bg=#1c1e2d"

# bell
set-window-option -g window-status-bell-style "fg=#151726,bg=#ee8679"

# style for window titles with activity
set-window-option -g window-status-activity-style "fg=#dee0ef,bg=#151726"

# style for command messages
set-option -g message-command-style "fg=#dee0ef,bg=#1c1e2d"

# Optional active/inactive pane state
# BASE16_TMUX_OPTION_ACTIVE is a legacy variable
if-shell '[ "$TINTED_TMUX_OPTION_ACTIVE" = "1" ] || [ "$BASE16_TMUX_OPTION_ACTIVE" = "1" ]' {
  set-window-option -g window-active-style "fg=#dee0ef,bg=#151726"
  set-window-option -g window-style "fg=#dee0ef,bg=#151726"
}

# Optional statusbar
# BASE16_TMUX_OPTION_STATUSBAR is a legacy variable
if-shell '[ "$TINTED_TMUX_OPTION_STATUSBAR" = "1" ] || [ "$BASE16_TMUX_OPTION_STATUSBAR" = "1" ]' {
  set-option -g status "on"
  set-option -g status-justify "left"
  set-option -g status-left "#[fg=#dee0ef,bg=#1c1e2d] #S #[fg=#1c1e2d,bg=#151726,nobold,noitalics,nounderscore]"
  set-option -g status-left-length "80"
  set-option -g status-left-style none
  set-option -g status-right "#[fg=#1c1e2d,bg=#151726 nobold, nounderscore, noitalics]#[fg=#8d8f9e,bg=#1c1e2d] %Y-%m-%d  %H:%M #[fg=#dee0ef,bg=#1c1e2d,nobold,noitalics,nounderscore]#[fg=#151726,bg=#dee0ef] #h "
  set-option -g status-right-length "80"
  set-option -g status-right-style none
  set-window-option -g window-status-current-format "#[fg=#151726,bg=#a78bfa,nobold,noitalics,nounderscore]#[fg=#1c1e2d,bg=#a78bfa] #I #[fg=#1c1e2d,bg=#a78bfa,bold] #W#{?window_zoomed_flag,*Z,} #[fg=#a78bfa,bg=#151726,nobold,noitalics,nounderscore]"
  set-window-option -g window-status-format "#[fg=#151726,bg=#1c1e2d,noitalics]#[fg=#dee0ef,bg=#1c1e2d] #I #[fg=#dee0ef,bg=#1c1e2d] #W#{?window_zoomed_flag,*Z,} #[fg=#1c1e2d,bg=#151726,noitalics]"
  set-window-option -g window-status-separator ""
}

# vim: set ft=tmux tw=0:
