# Tinted8 Github Dark High Contrast
# Scheme author: Tinted Theming (https://github.com/tinted-theming)
# Template author: Tinted Theming: (https://github.com/tinted-theming)

# default statusbar colors
set-option -g status-style "fg=#ffffff,bg=#010409"

# default window title colors
set-window-option -g window-status-style "fg=#ffffff,bg=#010409"

# active window title colors
set-window-option -g window-status-current-style "fg=#f0b72f,bg=#010409"

# pane border
set-option -g pane-border-style "fg=#"
set-option -g pane-active-border-style "fg=#"

# message text
set-option -g message-style "fg=#ffffff,bg=#656c76"

# pane number display
set-option -g display-panes-active-colour "#"
set-option -g display-panes-colour "#656c76"

# clock
set-window-option -g clock-mode-colour "#71b7ff"

# copy mode highlight
set-window-option -g mode-style "fg=#b7bdc8,bg=#656c76"

# bell
set-window-option -g window-status-bell-style "fg=#010409,bg=#ff9492"

# style for window titles with activity
set-window-option -g window-status-activity-style "fg=#ffffff,bg=#010409"

# style for command messages
set-option -g message-command-style "fg=#ffffff,bg=#656c76"

# Optional active/inactive pane state
if-shell '[ "$TINTED_TMUX_OPTION_ACTIVE" = "1" ]' {
  set-window-option -g window-active-style "fg=#ffffff,bg=#010409"
  set-window-option -g window-style "fg=#ffffff,bg=#151b23"
}

# Optional statusbar
if-shell '[ "$TINTED_TMUX_OPTION_STATUSBAR" = "1" ]' {
  set-option -g status "on"
  set-option -g status-justify "left"
  set-option -g status-left "#[fg=#ffffff,bg=#656c76] #S #[fg=#656c76,bg=#010409,nobold,noitalics,nounderscore]"
  set-option -g status-left-length "80"
  set-option -g status-left-style none
  set-option -g status-right "#[fg=#656c76,bg=#010409 nobold, nounderscore, noitalics]#[fg=#b7bdc8,bg=#656c76] %Y-%m-%d  %H:%M #[fg=#ffffff,bg=#656c76,nobold,noitalics,nounderscore]#[fg=#010409,bg=#ffffff] #h "
  set-option -g status-right-length "80"
  set-option -g status-right-style none
  set-window-option -g window-status-current-format "#[fg=#010409,bg=#f0b72f,nobold,noitalics,nounderscore]#[fg=#656c76,bg=#f0b72f] #I #[fg=#656c76,bg=#f0b72f,bold] #W#{?window_zoomed_flag,*Z,} #[fg=#f0b72f,bg=#010409,nobold,noitalics,nounderscore]"
  set-window-option -g window-status-format "#[fg=#010409,bg=#656c76,noitalics]#[fg=#ffffff,bg=#656c76] #I #[fg=#ffffff,bg=#656c76] #W#{?window_zoomed_flag,*Z,} #[fg=#656c76,bg=#010409,noitalics]"
  set-window-option -g window-status-separator ""
}

# vim: set ft=tmux tw=0:
